pool:
  vmImage: ubuntu-latest

variables:
  project: LanfeustBridge.csproj
  configuration: Debug
  
steps:
  - task: UseDotNet@2
    displayName: 'Use .Net Core sdk '
    inputs:
      useGlobalJson: true
  
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '$(project)'
      arguments: '--configuration $(configuration)'
  
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '$(project)'
      arguments: '--configuration $(configuration)'
  
  - task: DotNetCoreCLI@2
    displayName: 'Install DEV certificate'
    inputs:
      command: custom
      custom: 'dev-certs'
      arguments: https
  
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: ClientApp
      verbose: false
  
  - task: Npm@1
    displayName: 'Test Front-End'
    inputs:
      command: custom
      workingDir: ClientApp
      verbose: false
      customCommand: 'run test-ci'
  
  - task: Npm@1
    displayName: 'End-to-End Tests'
    inputs:
      command: custom
      workingDir: ClientApp
      verbose: false
      customCommand: 'run e2e-ci'
  
  - task: PublishTestResults@2
    displayName: 'Publish Front-End Test Results'
    inputs:
      testResultsFiles: 'ClientApp/junit/*.xml'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()
  
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage from Front-End tests'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: 'ClientApp/coverage/cobertura-coverage.xml'
      reportDirectory: ClientApp/coverage/html
