pool:
  vmImage: ubuntu-latest

variables:
  configuration: Debug
  
steps:
  - task: UseDotNet@2
    displayName: 'Use .Net Core sdk '
    inputs:
      useGlobalJson: true
  
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      workingDir: LanfeustBridge.Server
      command: restore
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      workingDir: LanfeustBridge.Server
      arguments: '--configuration $(configuration)'
  
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      workingDir: Movement.Tests
      command: test
      arguments: '--configuration $(configuration) --coverage'
  
  - task: DotNetCoreCLI@2
    displayName: 'Install DEV certificate'
    inputs:
      command: custom
      custom: 'dev-certs'
      arguments: https
  
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: lanfeustbridge.client
      verbose: false
  
  - task: Npm@1
    displayName: 'Test Front-End'
    inputs:
      command: custom
      workingDir: lanfeustbridge.client
      verbose: false
      customCommand: 'run test-ci'
  
  - task: PublishTestResults@2
    displayName: 'Publish Front-End Test Results'
    inputs:
      testResultsFiles: 'lanfeustbridge.client/junit/*.xml'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()
  
  - task: PublishCodeCoverageResults@2
    displayName: 'Publish code coverage from Front-End tests'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: 'lanfeustbridge.client/coverage/lanfeustbridge.client/cobertura-coverage.xml'

  - task: Npm@1
    displayName: 'End-to-End Tests'
    inputs:
      command: custom
      workingDir: lanfeustbridge.client
      verbose: false
      customCommand: 'run e2e-ci'

  - task: PublishTestResults@2
    displayName: 'Publish test results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'lanfeustbridge.client/e2e-junit-results.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: 'End-To-End Tests'
    condition: succeededOrFailed()
